[project]
name = "event-venue-rec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ecs-logging>=2.2.0",
    "fastapi>=0.128.0",
]
